(function() {var implementors = {};
implementors["actix_net"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"actix_net/connector/struct.Connector.html\" title=\"struct actix_net::connector::Connector\">Connector</a>",synthetic:false,types:["actix_net::connector::Connector"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"actix_net/connector/trait.RequestPort.html\" title=\"trait actix_net::connector::RequestPort\">RequestPort</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"actix_net/connector/struct.TcpConnector.html\" title=\"struct actix_net::connector::TcpConnector\">TcpConnector</a>&lt;T&gt;",synthetic:false,types:["actix_net::connector::TcpConnector"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"actix_net/connector/struct.DefaultConnector.html\" title=\"struct actix_net::connector::DefaultConnector\">DefaultConnector</a>",synthetic:false,types:["actix_net::connector::DefaultConnector"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"actix_net/resolver/trait.RequestHost.html\" title=\"trait actix_net::resolver::RequestHost\">RequestHost</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"actix_net/resolver/struct.Resolver.html\" title=\"struct actix_net::resolver::Resolver\">Resolver</a>&lt;T&gt;",synthetic:false,types:["actix_net::resolver::Resolver"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"actix_net/server/struct.Server.html\" title=\"struct actix_net::server::Server\">Server</a>",synthetic:false,types:["actix_net::server::server::Server"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"actix_net/stream/struct.TakeItem.html\" title=\"struct actix_net::stream::TakeItem\">TakeItem</a>&lt;T&gt;",synthetic:false,types:["actix_net::stream::TakeItem"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"actix_net/time/struct.LowResTime.html\" title=\"struct actix_net::time::LowResTime\">LowResTime</a>",synthetic:false,types:["actix_net::time::LowResTime"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
