(function() {var implementors = {};
implementors["actix_net"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"actix_net/resolver/struct.ResolveError.html\" title=\"struct actix_net::resolver::ResolveError\">ResolveError</a>&gt; for <a class=\"enum\" href=\"actix_net/connector/enum.ConnectorError.html\" title=\"enum actix_net::connector::ConnectorError\">ConnectorError</a>",synthetic:false,types:["actix_net::connector::ConnectorError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>&gt; for <a class=\"enum\" href=\"actix_net/connector/enum.ConnectorError.html\" title=\"enum actix_net::connector::ConnectorError\">ConnectorError</a>",synthetic:false,types:["actix_net::connector::ConnectorError"]},{text:"impl&lt;E, U:&nbsp;<a class=\"trait\" href=\"https://docs.rs/tokio-io/0.1.10/tokio_io/codec/encoder/trait.Encoder.html\" title=\"trait tokio_io::codec::encoder::Encoder\">Encoder</a> + <a class=\"trait\" href=\"https://docs.rs/tokio-io/0.1.10/tokio_io/codec/decoder/trait.Decoder.html\" title=\"trait tokio_io::codec::decoder::Decoder\">Decoder</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;E&gt; for <a class=\"enum\" href=\"actix_net/framed/enum.FramedTransportError.html\" title=\"enum actix_net::framed::FramedTransportError\">FramedTransportError</a>&lt;E, U&gt;",synthetic:false,types:["actix_net::framed::FramedTransportError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
